#!/usr/bin/env bash
# Instaling Nginx

echo -e " Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y
sudo service nginx start

# By default FireWall blocks the incoming traffic over HTTP
# on Nginx for security reasons, so we need to allowing this
echo -e "\nAllowing incoming traffic through HTTP...\n"
sudo ufw allow 'Nginx HTTP'

echo -e "\n\t>>> Backing up files & Setting up configurations...\n"

# Give ownership to the user for easy accessing and editing and backing up
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.backup

# Task 1: Hello World
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\nCompleted.\n"
