#!/usr/bin/env bash
# This script listens on port 98 on localhost and echoes received text.

# Check if the 'nc' command is available
if ! command -v nc &>/dev/null; then
	echo "Error: 'nc' (netcat) command is not available. Please install it."
	exit 1
fi

# Start listening on port 98 and echo received text
while true; do
	{ echo -ne "HTTP/1.1 200 OK\r\n\r\n$(date)\r\n"; } | nc -l -p 98 -q 1
done
